In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("mk_data.csv")
df.shape

(2240, 28)

In [4]:
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Response', 'Complain', 'Country'],
      dtype='object')

In [13]:
df["Income"] = df["Income"].str.strip().str.replace(",", "").str.replace("$", "").astype(float)

In [ ]:
df.describe(include="object")

         Education Marital_Status      Income Dt_Customer Country
count         2240           2240        2216        2240    2240
unique           5              8        1974         663       8
top     Graduation        Married  $7,500.00      8/31/12      SP
freq          1127            864          12          12    1095

In [ ]:
def get_outliers(col): 
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lim_sup = Q3 + 1.5*IQR

    outliers = df[df[col]>lim_sup]
    return outliers
get_outliers("Income")

In [ ]:
def get_outliers_2(serie): 
    Q1 = serie.quantile(0.25)
    Q3 = serie.quantile(0.75)
    IQR = Q3 - Q1

    lim_sup = Q3 + 1.5*IQR

    outliers = serie[serie>lim_sup]
    return outliers

get_outliers_2(df["Income"])

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,Complain,Country
35,7962,1987,PhD,Single,95169.0,0,0,10/9/13,1,1285,...,4,1,0,0,1,1,0,1,0,SP
38,3725,1961,PhD,Single,84865.0,0,0,5/9/13,1,1248,...,9,4,0,1,1,1,1,1,0,SP
77,7919,1976,PhD,Together,72335.0,0,0,8/13/12,2,1285,...,8,8,0,0,0,0,0,1,0,SP
152,8545,1954,Graduation,Divorced,85683.0,0,0,3/21/14,6,1296,...,10,1,0,1,1,1,1,1,0,SP
196,3009,1962,PhD,Widow,71670.0,0,0,7/9/13,8,1462,...,6,6,0,1,1,0,1,1,0,SP
222,5547,1982,PhD,Married,84169.0,0,0,8/7/13,9,1478,...,6,3,0,1,1,0,0,1,0,SP
223,8362,1982,PhD,Married,84169.0,0,0,8/7/13,9,1478,...,6,3,0,1,1,0,0,1,0,SA
376,10133,1970,Graduation,Single,93790.0,0,0,2/12/14,16,1302,...,12,2,0,1,1,1,0,1,0,CA
402,7999,1955,PhD,Together,75261.0,0,0,4/23/13,17,1239,...,5,2,0,1,1,0,0,1,0,SP
472,9260,1945,PhD,Married,70356.0,0,0,11/5/12,20,1349,...,9,6,0,0,0,0,0,0,0,CA
624,10140,1983,PhD,Together,70123.0,0,0,9/28/13,27,1308,...,4,3,0,1,0,0,1,0,0,IND
722,5236,1979,Graduation,Together,77568.0,0,1,8/25/12,30,1230,...,8,5,0,1,1,1,0,0,0,SP
924,7431,1991,PhD,Single,68126.0,0,0,11/10/12,40,1332,...,5,9,0,1,0,0,0,1,0,CA
1003,1204,1970,PhD,Married,67536.0,0,1,5/22/13,45,1253,...,11,8,0,0,0,1,0,0,0,SA
1026,4580,1969,Graduation,Married,75759.0,0,0,10/25/13,46,1394,...,9,5,1,0,1,1,0,1,0,SA
1054,6248,1947,Master,Single,91712.0,0,0,10/17/13,47,1276,...,11,3,0,0,1,0,0,1,0,SP
1058,203,1975,Master,Single,81169.0,0,0,4/14/13,47,1288,...,9,2,0,0,0,0,0,0,0,SP
1293,737,1949,PhD,Married,80360.0,0,0,3/3/13,56,1493,...,5,2,0,1,1,1,0,0,0,SP
1369,6292,1986,PhD,Married,82333.0,0,0,3/30/13,60,1311,...,10,2,0,0,1,0,0,1,0,GER
1376,1103,1976,Master,Married,81929.0,1,0,9/29/12,60,1486,...,10,6,1,0,1,0,0,1,0,AUS
1385,3174,1959,Graduation,Together,87771.0,0,1,5/22/13,61,1492,...,4,6,0,1,1,1,1,1,0,SP
1386,5536,1959,Graduation,Together,87771.0,0,1,5/22/13,61,1492,...,4,6,0,1,1,1,1,1,0,CA
1404,1763,1988,Graduation,Together,87679.0,0,0,7/27/13,62,1259,...,10,4,1,0,1,1,0,1,0,CA
1417,2926,1952,Master,Together,55951.0,0,1,8/23/12,62,1241,...,11,8,0,1,0,0,1,0,0,SA
1584,7899,1952,PhD,Married,77610.0,0,1,10/29/12,70,1245,...,4,7,0,0,0,0,0,0,0,AUS
1596,1665,1964,PhD,Divorced,64140.0,0,2,9/23/13,71,1459,...,6,5,1,0,1,0,1,1,0,SA
1661,4943,1953,Graduation,Married,70503.0,0,0,9/30/12,73,1379,...,9,6,0,1,1,0,0,0,0,SP
1740,6932,1941,PhD,Married,93027.0,0,0,4/13/13,77,1285,...,5,2,0,0,1,0,0,0,0,SP
1844,8732,1969,Master,Widow,67369.0,0,1,11/17/12,81,1298,...,10,4,0,1,1,0,0,1,0,SP
1864,4475,1949,PhD,Married,69098.0,0,0,2/16/13,82,1315,...,9,5,0,0,0,0,0,0,0,SP
1885,11088,1971,PhD,Together,78642.0,0,1,4/21/13,83,1396,...,4,6,0,0,0,0,0,0,0,SP
1913,3138,1956,Graduation,Single,91249.0,0,0,10/20/12,84,1324,...,6,4,0,1,1,1,1,1,0,SP
1930,9743,1955,Graduation,Married,76998.0,0,1,1/11/13,85,1449,...,8,6,0,0,1,0,0,0,0,CA
2002,9298,1947,PhD,Together,81574.0,0,0,4/28/14,89,1252,...,8,1,0,1,1,0,0,0,0,SA
2192,9499,1954,Graduation,Married,93404.0,1,2,5/7/13,97,1279,...,7,5,0,1,1,0,0,0,0,CA