# Clase 2 — Semana 1: Introducción a Pandas 2  
**Autor:** Robert Moreno  

> **Objetivo:** Reforzar lectura de datos, tipos (`dtype`), estadísticos básicos, conteos, `unique/nunique`, y limpieza de strings con `.str`.

## 0) Preparación

Seguimos trabajando con **`personas.csv`**.

**Hints:**
- Guarda `personas.csv` en la **misma carpeta** que el notebook.
- En **Google Colab**, sube el archivo antes de leerlo.
- Si el separador no es coma, usa `sep=...` (por ejemplo `sep=";"`).

## 1) Leer el dataset

**Ejercicio 1:** Lee `personas.csv` y guárdalo en una variable llamada `df`.  
Luego muestra `df.head()`.

**Hint:** `pd.read_csv("personas.csv",sep = "|")`

In [1]:
# Tu solución aquí
import pandas as pd

df = pd.read_csv("personas.csv", sep = "|")
df.sample(5)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email
52745,2449220074,Fernanda Paredes Zambrano,NaN,168.2,148.1,F,1261.22,Salinas,2024-03-17,Universidad,NaN
42447,1705804498,camila espinoza sanchez,33.0,175.3,162.2,m,614.74,Quito,2025-11-04,Secundaria,NaN
3534,144959392,ALEJANDRA ESPINOZA HERRERA,27.0,164.3,158.2,f,480.00,Cuenca,13/11/2024,Universidad,alejandra.espinoza.herrera@outlook.com
26966,1034695724,Natalia Guerrero Navarro,30.0,158.8,114.6,f,480.00,Ibarra,2024-03-06,Universidad,.natalia.guerrero.navarro@gmail.com
22182,911084671,DIEGO BRAVO CHÁVEZ,44.0,183.7,188.8,m,480.00,Guayaquil,2024-05-11,Secundaria,diego.bravo.chavez@outlook.com

## 2) Re-leer el dataset usando `dtype` para no perder ceros

Se identificó que la **identificación** (tipo cédula) de Guayaquil puede **perder el 0 inicial** (por ejemplo `09...`) si Pandas la lee como número.

**Ejercicio 2:** Vuelve a leer el CSV, pero esta vez asegurando que la columna `identificacion` se lea como texto.

**Hint:**
- Usa el parámetro `dtype`:
  - `dtype={"identificacion": "string"}`  (recomendado)
  - o `dtype={"identificacion": str}`

In [2]:
# Tu solución aquí
df = pd.read_csv("personas.csv", 
                 sep = "|", 
                 dtype={"identificacion": "string"})
df.sample(10)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email
14489,0947303939001,Camila Sanchez Rodriguez,40.0,181.9,203.7,M,882.20,Guayaquil,2024-07-24,Tecnico,camila.sanchez.rodriguez@hotmail.com
53481,2441157456001,ALEJANDRO CORNEJO SALAZAR,26.0,165.3,155.1,f,845.99,Salinas,06/12/2023,Universidad,alejandro.cornejo.salazar@gmail.com
41006,1732917834,ISABELA DELGADO CRUZ,32.0,178.6,163.9,m,489.12,Quito,2025-11-20,Primaria,isabela.delgado.cruz@outlook.com
38351,1348318047,camila peña tapia,31.0,171.7,124.7,f,929.32,Portoviejo,2026-01-11,Secundaria,camila.pena.tapia@yahoo.com
39732,1257564417,natalia carrillo garcía,46.0,171.9,137.7,M,480.00,Quevedo,2025-07-08,Maestria,.natalia.carrillo.garcia@empresa.ec
15758,0929819845001,Karen Valencia Ortega,36.0,165.5,160.8,m,480.00,Guayaquil,"Dec 10, 2025",Tecnico,NaN
21499,0929254563,cristian navarro mendoza,49.0,172.3,168.3,F,506.18,Guayaquil,"May 23, 2025",Primaria,cristian.navarro.mendoza@outlook.com
48768,1712406386,PEDRO ACOSTA CORNEJO,28.0,163.9,145.7,f,933.73,Quito,"Dec 17, 2023",Universidad,pedro.acosta.cornejo@outlook.com
10255,0827238999001,Pedro Salazar Tapia,36.0,176.0,171.4,m,545.92,Esmeraldas,2024-04-07,Maestria,pedro.salazar.tapia@hotmail.com
17891,0935035238001,Mateo Zambrano Arévalo,36.0,162.3,149.9,m,597.90,Guayaquil,30/07/2023,Secundaria,mateo.zambrano.arevalo@empresa.ec

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55107 entries, 0 to 55106
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   identificacion   55107 non-null  string
 1   nombre           55107 non-null  object
 2   edad             53537 non-null  float64
 3   altura_cm        55107 non-null  float64
 4   peso_lb          55107 non-null  float64
 5   sexo             55107 non-null  object
 6   salario          55107 non-null  float64
 7   ciudad           55107 non-null  object
 8   fecha_registro   51831 non-null  object
 9   nivel_educacion  55107 non-null  object
 10  email            32050 non-null  object
dtypes: float64(4), object(6), string(1)
memory usage: 4.6+ MB

## 3) Promedio de edad

**Ejercicio 3:** ¿Cuál es el **promedio de edad** de las personas?

**Nota:**
- Si hay nulos, `mean()` por defecto los ignora.

In [4]:
# Tu solución aquí
df["edad"].mean()

np.float64(36.70609111455629)

In [5]:
print(df["salario"].min())
print(df["salario"].max())

480.0
4190.31

## 4) Salario mínimo, promedio y máximo

**Ejercicio 4:** Calcula:
- salario mínimo
- salario promedio
- salario máximo

**Hints:**
- `min()`, `mean()`, `max()`
- También puedes usar `describe()`

In [6]:
# Tu solución aquí
# Coloca prints en cada linea para que se impriman los 3 valores c:
# Osea print(df[..].min())
print("Salario mínimo:" , df["salario"].min())
print("Salario promedio:", df["salario"].mean())
print("Salario máximo:", df["salario"].max())

Salario mínimo: 480.0
Salario promedio: 785.8401560600288
Salario máximo: 4190.31

In [7]:
df["salario"].describe()

count    55107.000000
mean       785.840156
std        421.885007
min        480.000000
25%        480.000000
50%        632.180000
75%        928.700000
max       4190.310000
Name: salario, dtype: float64

In [8]:
df.describe()

               edad     altura_cm       peso_lb       salario
count  53537.000000  55107.000000  55107.000000  55107.000000
mean      36.706091    170.709509    157.761310    785.840156
std        6.400502      8.728430     26.881768    421.885007
min       21.000000    145.000000     95.000000    480.000000
25%       32.000000    164.400000    138.000000    480.000000
50%       36.000000    170.600000    157.400000    632.180000
75%       41.000000    176.900000    177.400000    928.700000
max       63.000000    204.700000    270.400000   4190.310000

In [9]:
#df["ciudad"].nunique() # nunique para el numero unico
#df["nivel_educacion"].unique() # unique para mostrar los valores unicos
df["nivel_educacion"].value_counts()

nivel_educacion
Universidad    19760
Secundaria     16551
Tecnico         9867
Maestria        5632
Primaria        3297
Name: count, dtype: int64

## 5) `unique()` y `nunique()`

**Ejercicio 5:** Practiquemos con estas columnas:

5.1) ¿Cuáles son los valores únicos de `ciudad`? (`unique()`)  

**Hints:**
- `df["col"].unique()`

In [10]:
df["ciudad"].unique()

array(['Ambato', 'Cuenca', 'Esmeraldas', 'Guayaquil', 'Ibarra', 'Loja',
       'Machala', 'Manta', 'Portoviejo', 'Quevedo', 'Quito', 'Riobamba',
       'Salinas', 'Santo Domingo'], dtype=object)

# Tu solución aquí

5.2) ¿Cuántas ciudades diferentes hay? (`nunique()`)  

**Hints:**

- `df["col"].nunique()`

In [11]:
# Tu solución aquí
df["ciudad"].nunique()

14

5.3) Repite lo mismo para `nivel_educacion`.

In [12]:
# Tu solución aquí
df["nivel_educacion"].nunique()

5

## 6) Limpieza de strings con `.str`

En el dataset, `sexo` puede venir como `M, m, F, f` y `nombre` puede tener espacios extra y case inconsistente.

**Ejercicio 6:**
1) Actualice la columna `sexo` colocandola en mayúsculas usando `.str.upper()`

In [13]:
df["sexo"].unique()

array(['F', 'm', 'M', 'f'], dtype=object)

In [14]:
# Tu solución aquí
df["sexo"] = df["sexo"].str.upper()
df["sexo"].unique()

array(['F', 'M'], dtype=object)

In [15]:
#del df["sexo_clean"] # Si la columna no existe, da error.

2) Crea una columna `nombre_clean` aplicando:
   - `.str.strip()` para quitar espacios al inicio y final
   - `.str.title()` para formato de nombre

In [16]:
# Tu solución aquí
df["nombre_clean"] = df["nombre"].str.strip().str.title()
df.head(3)

,identificacion,nombre,edad,altura_cm,peso_lb,sexo,salario,ciudad,fecha_registro,nivel_educacion,email,nombre_clean
0,1842222836,Paola Mera Rodriguez,31.0,166.4,141.8,F,480.00,Ambato,28/03/2023,Secundaria,NaN,Paola Mera Rodriguez
1,1829202652,isabela molina silva,39.0,167.8,166.2,M,480.00,Ambato,20/08/2025,Tecnico,isabela.molina.silva@gmail.com,Isabela Molina Silva
2,1801036961,Fernanda Reyes Benítez,31.0,177.4,195.7,M,605.28,Ambato,"Apr 05, 2025",Secundaria,NaN,Fernanda Reyes Benítez

## 7) ¿Cuántos hombres y mujeres hay?

**Ejercicio 7:** Usa `.value_counts()` para contar cuántos hay de cada sexo (usa `sexo_clean`).

In [17]:
# Tu solución aquí
df["sexo"].value_counts()

sexo
M    28538
F    26569
Name: count, dtype: int64

## 8) ¿Qué porcentaje representa cada sexo?

**Ejercicio 8:** Usa `value_counts(normalize=True)` para obtener proporciones.  
Luego multiplícalo por 100 para porcentaje.

In [18]:
porcentajes = df["sexo"].value_counts(normalize = True)*100
porcentajes = porcentajes.round(2).astype("str") + "%"

In [19]:
porcentajes

sexo
M    51.79%
F    48.21%
Name: proportion, dtype: object

In [20]:
#df["salario"] = df["salario"].str.replace("$", "").astype("float")

In [21]:
df["sexo"].str.replace("F", "Female").str.replace("M", "Male")

0        Female
1          Male
2          Male
3        Female
4          Male
          ...
55102      Male
55103      Male
55104    Female
55105      Male
55106    Female
Name: sexo, Length: 55107, dtype: object

## 9) Crear datasets separados: mujeres y hombres

**Ejercicio 9:** Crea:
- `df_mujeres` (solo mujeres)
- `df_hombres` (solo hombres)

**Hints:**
- Mujeres: `df[df["sexo"] == "F"]`
- Hombres: `df[df["sexo"] == "M"]`

In [22]:
#df[condicion]

In [23]:
# Tu solución aquí
df_mujeres = df[df["sexo"] == "F"]
df_hombres = df[df["sexo"] == "M"]

#print(df_mujeres.head(2))
#print(df_hombres.head(2))

## 10) Promedio de altura de mujeres

**Ejercicio 10:** Calcula el promedio de `altura_cm` en `df_mujeres`.

**Hint:** `df_mujeres["altura_cm"].mean()`

In [24]:
# Tu solución aquí
df_mujeres["altura_cm"].mean()

np.float64(164.98011968835866)

## 11) Promedio de altura de hombres

**Ejercicio 11:** Calcula el promedio de `altura_cm` en `df_hombres`.

In [25]:
# Tu solución aquí
df_hombres["altura_cm"].mean()

np.float64(176.04359450557152)

## 12) ¿Quién gana más: hombres o mujeres?

**Ejercicio 12:** Compara el salario promedio entre `df_hombres` y `df_mujeres`.


✅ Responde con un comentario: `# En promedio ganan más ...`

In [26]:
# Tu solución aquí
# salario_prom_hombres = ...
# salario_prom_mujeres = ...

# Respuesta (comentario):
#

## 13) Reconocer nulos y valores duplicados
**Ejercicio 13.1:** Utilizando `.isna().sum()` encuentre la cantidad de valores nulos para cada columna

In [27]:
# Tu solución aquí
df.isna().sum()

identificacion         0
nombre                 0
edad                1570
altura_cm              0
peso_lb                0
sexo                   0
salario                0
ciudad                 0
fecha_registro      3276
nivel_educacion        0
email              23057
nombre_clean           0
dtype: int64

**Ejercicio 13.2:** Utilizando `.duplicated().sum()` encuentre la cantidad de filas duplicadas. De haberlas, elimínelas usando `.drop_duplicates()`

In [28]:
# Tu solución aquí
#df.duplicated().sum() ## evalua cuantas filas estan repetidas

# Solo viendo duplicados en el campo de identificacion
df.duplicated(subset= ["identificacion"]).sum()

np.int64(1232)

In [29]:
#df[df.duplicated()] #filtrar solo duplicados
df = df.drop_duplicates().reset_index(drop = True)

## 14) Preguntas interesantes (solo escribirlas) 👀

**Ejercicio 14:** Revisa el dataset (columnas y lo que has observado) y propone **4 preguntas** de análisis que te parezcan interesantes.

📌 Importante:
- **Solo escribe las preguntas como comentarios**.
- No necesitas codificarlas todavía.
- Pueden ser preguntas de negocio, sociales o de calidad de datos.

Ejemplo (solo como idea):  
- ¿El salario cambia según el nivel de educación?

In [30]:
#df.head()

In [31]:
# Escribe aquí 4 preguntas interesantes (solo comentarios):
# 1)
# 2)
# 3)
# 4)

---  
### (Opcional)  
Si sientes que con los conocimientos adquiridos hasta el momento, puedes responder una o más preguntas, adelante c:

In [33]:
df.to_csv("personas_clean.csv", sep = ",", index = False)